require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
target 'LightNowApp' do
 
config = use_native_modules!


  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNSoundRecorder', :path => '../node_modules/react-native-sound-recorder'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'LightNowAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'LightNowApp-tvOS' do
  # Pods for LightNowApp-tvOS

  target 'LightNowApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
